bill-bug-fix-1
Real-Dev-Squad/website-crypto pull request #123
Opened 2021-01-28 14:49 UTC by kachwalUttamsharma

created new generic .js file for handling click outside modal, to close modal. which takes ref and callback function as argument.

open for suggestions.

2021-01-29 14:39 UTC, PremanandChowdhury commented
@kachwalUttamsharma  
- Add the **GenericClosePopUp** Component to the other pop-ups too (like the profile image dropdown and filter in the homepage).

2021-01-29 15:13 UTC, kachwalUttamsharma commented
> @kachwalUttamsharma
> 
> * Add the **GenericClosePopUp** Component to the other pop-ups too (like the profile image dropdown and filter in the homepage).

working on it

2021-01-30 08:39 UTC, PremanandChowdhury submitted a review, later dismissed
Thanks @kachwalUttamsharma 🚀

2021-02-02 10:17 UTC, PremanandChowdhury commented
@kachwalUttamsharma Resolve the conflicts. 👍🏼

2021-02-02 11:04 UTC, kachwalUttamsharma commented
> @kachwalUttamsharma Resolve the conflicts. 👍🏼 

Ok

2021-02-02 14:09 UTC, PremanandChowdhury approved these changes

2021-02-02 17:11 UTC, Kratika0907 requested changes
Looks good. Can you please name the ref variable correctly. Everywhere it is const ref = ref.
We can have something like const billRef = ref.

2021-02-03 03:02 UTC, kachwalUttamsharma commented
> an you please name the ref variable correctly. Everywhere it is const ref = ref.
> We can have something like const billRef = ref.

sure, working on it.

2021-02-03 06:28 UTC, PremanandChowdhury approved these changes
LGTM👍

2021-02-09 15:50 UTC, Kratika0907 approved these changes

2021-02-09 15:50 UTC, merged

2021-04-24 15:11 UTC, ankushdharkar commented on components/filter/index.js
> +        </div>
<li> inside a <div>?