fixed an issue
Real-Dev-Squad/website-crypto pull request #207
Opened 2021-06-06 11:43 UTC by Devashish0210

fixed an issue where even if the user had 0 stocks of a certain company, the stock card of that company would still show with quantity 0. so instead of that, a message saying "You don't have any stocks yet. Click below to buy some" has been added.

2021-06-06 12:01 UTC, swarajpure requested changes
Requesting a change in variable name.
Please check.

Good job! ⚡

2021-06-06 12:01 UTC, swarajpure commented on pages/trading/sell.js
> +  const Message = "You don't have any stocks yet. Click below to buy some";
Also, this better to be declared at the top of the file

2021-06-07 12:02 UTC, Devashish0210 commented
![Initial](https://user-images.githubusercontent.com/69790529/121013217-2f82ab00-c7b6-11eb-8b92-60b0e275d8a1.jpg)
As we can see in the initial image, even if the user does not own any stocks of the company, the company card along with "Quantity : 0" is still unwantedly mentioned there. That has been changed, the cards have been removed if the user does not own any stocks and a simple message has been inserted telling the user to buy more stocks. See image below for reference.
![Final Render](https://user-images.githubusercontent.com/69790529/121013241-36112280-c7b6-11eb-9fe4-9438104c1ad0.png)

2021-06-07 12:05 UTC, Devashish0210 commented
![Initial](https://user-images.githubusercontent.com/69790529/121013624-b20b6a80-c7b6-11eb-8cb1-2f0dd511c0a0.jpg)
As we can see in the initial image, even if the user does not own any stocks of the company, the company card along with "Quantity : 0" is still unwantedly mentioned there. That has been changed, the cards have been removed if the user does not own any stocks and a simple message has been inserted telling the user to buy more stocks. See image below for reference.
![Final Render](https://user-images.githubusercontent.com/69790529/121013633-b8014b80-c7b6-11eb-95e6-0f0b7306f6e5.png)

2021-06-07 12:09 UTC, Devashish0210 commented
![Initial](https://user-images.githubusercontent.com/69790529/121014105-3827b100-c7b7-11eb-8294-99f5f98143f6.jpg)
As we can see in the initial image, even if the user does not own any stocks of the company, the company card along with "Quantity : 0" is still unwantedly mentioned there. That has been changed, the cards have been removed if the user does not own any stocks and a simple message has been inserted telling the user to buy more stocks. See image below for reference.
![Final Render](https://user-images.githubusercontent.com/69790529/121014128-407fec00-c7b7-11eb-8f2f-c0ac90fe50de.png)

2021-06-07 12:11 UTC, Devashish0210 commented
![Initial](https://user-images.githubusercontent.com/69790529/121014340-7f15a680-c7b7-11eb-96f6-6bf5747d455a.png)
As we can see in the initial image, even if the user does not own any stocks of the company, the company card along with "Quantity : 0" is still unwantedly mentioned there. That has been changed, the cards have been removed if the user does not own any stocks and a simple message has been inserted telling the user to buy more stocks. See image below for reference.
![Final Render](https://user-images.githubusercontent.com/69790529/121014365-8472f100-c7b7-11eb-8c48-1a16c4ff1432.png)

2021-06-16 12:34 UTC, swarajpure approved these changes
Looks good to me.

Thanks!

2021-06-16 12:34 UTC, merged