Contribution.md file updated
Real-Dev-Squad/website-crypto pull request #251
Opened 2022-02-02 15:35 UTC by DeRaowl

updated contribution.ms file with required changes

2022-02-03 09:20 UTC, rajat-mehra05 requested changes
Please review the comments, do the needful and resolve the conversation afterwards.

2022-02-03 09:20 UTC, rajat-mehra05 commented on CONTRIBUTING.md
>  1. **Forking repository**
Can you add `description` for `Forking repository` for this website from the reference given along with the image ?
Like this but for `crypto-site`:

![image](https://user-images.githubusercontent.com/35677839/152313383-bf01f8c6-b584-4604-984d-928fb357d8df.png)

2022-02-03 09:20 UTC, rajat-mehra05 commented on CONTRIBUTING.md
>  git commit -m "Write message about your commit"
Don't we require to add this command before the commit message `git add .` ?

2022-02-03 12:07 UTC, akshay1502 commented on CONTRIBUTING.md
>  ```
Do we need ``` here?
You can check the preview of markdown file by following [this](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview).
![Firefox_Screenshot_2022-02-03T12-01-18 781Z](https://user-images.githubusercontent.com/55057874/152339167-19c3bcce-cbab-47ce-bb2f-2f5069a5e99c.png)

2022-02-04 07:44 UTC, rajat-mehra05 approved these changes
Looks good to me.

2022-02-04 09:04 UTC, akshay1502 approved these changes

2022-02-04 09:05 UTC, akshay1502 commented
Thanks for the PR @DeRaowl .

2022-02-04 09:08 UTC, merged