layout changed for home page
Real-Dev-Squad/website-crypto pull request #49
Opened 2020-10-11 20:56 UTC by Kratika0907

Layout changed for home page
Filter logic removed from main component
Link added for shop and cart

2020-10-13 09:20 UTC, swarajpure reviewed
Reviewed for the commented code.

2020-10-13 09:20 UTC, swarajpure commented on components/coins-status/index.js
> +            //justify-content: space-evenly;
Commented code... Are you sure if we need this?

2020-10-13 09:20 UTC, swarajpure commented on styles/Home.module.css
> +/* .header {
One more commented code..

2020-10-13 14:43 UTC, sumitd94 approved these changes

2020-10-14 01:52 UTC, whyDontI requested changes

2020-10-14 01:52 UTC, whyDontI commented on styles/Home.module.css
> +    grid-column: 4 ;
Fix indentation for this file. Also please remove redundant blank lines if not removed by linter itself.

2020-10-14 01:52 UTC, whyDontI commented on pages/index.js
> + <div className={`${styles.card}`}>
Indentation needs to be done here

2020-12-08 17:59 UTC, closed without merging