Graph fix css
Real-Dev-Squad/website-crypto pull request #97
Opened 2020-12-25 20:24 UTC by Kratika0907

Transaction graph css fix. (Responsive)

2020-12-25 22:50 UTC, ankushdharkar requested changes

2020-12-25 22:50 UTC, ankushdharkar commented on components/coins-status/coin.module.css
> +.cointypeIndicator {
If this PR depends on some other PR, please mention it in the description.

2021-01-01 10:29 UTC, whyDontI commented
- Can you put some screenshots of the changes?
- And you might want to run `eslint --fix .` once, it will solve a lot of linting issues like `unnecessary blank lines`, `Indentation`, etc.

2021-01-01 10:35 UTC, whyDontI requested changes
- Can you put some screenshots of the changes?
- And you might want to run `eslint --fix .` once, it will solve a lot of linting issues like `unnecessary blank lines`, `Indentation`, etc.

2021-01-18 18:45 UTC, closed without merging