Swapped position of the - and + buttons on the shop page
Real-Dev-Squad/website-crypto pull request #99
Opened 2020-12-27 05:49 UTC by JoseLRiano

![Screen Shot 2020-12-27 at 12 45 36 AM](https://user-images.githubusercontent.com/24719862/103164776-64d5a680-47dd-11eb-8e11-4b05ab8e4811.png)

2020-12-27 18:39 UTC, ankushdharkar requested changes

2020-12-27 18:39 UTC, ankushdharkar commented on package.json
>  }
I don't think we need to update package.json for this change. Please remove these changes

2020-12-27 19:17 UTC, ankushdharkar approved these changes
Thank you for the changes @JoseLRiano! The changes will eventually show up on https://crypto.realdevsquad.com/shop

If you want to work more on such projects with us, please consider joining [our Discord](https://discord.gg/ge6NXX6wEQ)

2020-12-27 19:18 UTC, merged

2020-12-27 19:21 UTC, JoseLRiano commented
Hi Ankush, I just remove those changes and push it to the branch I created.

On Sun, Dec 27, 2020 at 1:39 PM Ankush Dharkar <notifications@github.com>
wrote:

> Assigned #99 <https://github.com/Real-Dev-Squad/website-crypto/pull/99>
> to @JoseLRiano <https://github.com/JoseLRiano>.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Real-Dev-Squad/website-crypto/pull/99#event-4150500225>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF4TD5RPBAOGEEPASE7ZAILSW55OTANCNFSM4VKQ2YSA>
> .
>

2020-12-28 05:14 UTC, ankushdharkar commented
Hello @JoseLRiano, 

I already accepted your PR. Thank you 🎉! It's merged into develop